Adding ThermoPoromechanics solver
GEOSX/GEOSX pull request #1655
Opened 2021-10-22 13:26 UTC by sytuannguyen

This PR adds a solver for the Thermo-Poromechanics coupled problems. It bases on the existing Poromechanics solver and adds the thermal field to it.

2022-08-18 08:26 UTC, sytuannguyen commented
This PR is closed and will be replaced by another one with updated codebase

2022-08-26 09:36 UTC, sytuannguyen commented
I reopen this PR after resolving all the conflicts and updating the THM solver to follow up with the changes in the codebase during the last ten months.

2022-08-26 22:08 UTC, herve-gross commented on host-configs/xraiTotal.cmake
> +site_name(HOST_NAME)
We should leave this file out of the pull request

2022-08-26 22:09 UTC, herve-gross commented on src/coreComponents/linearAlgebra/interfaces/hypre/HypreMGR.cpp
> +/**
these merge conflict information lines should be removed (many other)

2022-08-26 22:11 UTC, herve-gross commented on src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsKernel.hpp
> +/**
merge info - please remove

2022-08-26 22:15 UTC, herve-gross requested changes
There are still a lot of merge conflicts in these files. @francoishamon and @TotoGaz - can you  take a look and help with this PR?

2022-08-26 22:15 UTC, herve-gross commented on src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsKernel.hpp
> +/**
merge info - please remove. Also, did you run uncrustify?

2022-08-26 22:15 UTC, herve-gross commented on src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsKernel.hpp
> +/**
merge info - please remove

2022-08-27 02:32 UTC, francoishamon reviewed
Hello @sytuannguyen it is great to have you back.

After you left, we implemented a thermal option in the flow solvers (single-phase and compositional) with temperature defined at the cell centers. The work in your PR is great, but it is taking an approach that we tried to avoid in the thermal flow solvers, i.e., duplicating the entire solver, and all the assembly kernels, just to add a thermal option.

To make sure that your work fits into the existing thermal framework, we should probably take some time to think about a good design before going forward with your PR, and maybe start with a simple thermal constitutive model? We could discuss that in a meeting if you want, or using the thermoporomechanics slack channel, whatever is easier for you.

2022-08-29 00:07 UTC, joshua-white commented
Hi @sytuannguyen.  Yes, in the intervening time @frankfeifan and @CusiniM have already made significant progress on a thermoporomechanics solver.  Let's arrange a meeting to discuss how you can best contribute to the code moving forward.

2022-08-29 00:23 UTC, frankfeifan commented
> Hi @sytuannguyen. Yes, in the intervening time @frankfeifan and @CusiniM have already made significant progress on a thermoporomechanics solver. Let's arrange a meeting to discuss how you can best contribute to the code moving forward.

Yes. More specifically, @CusiniM and I have recently added a ThermalSinglePhaseFlow solver by adding the thermal option in the original SinglePhaseFlow solver. I am now also woking on a ThermalPoromechanics solver by sequentially coupling the existing ThermalSinglePhaseFlow solver and the SolidMechanics solver, and about to test it. I agree that we should arrange a meeting to discuss how to proceed.

2022-08-29 06:27 UTC, sytuannguyen commented
Hello @herve-gross, @francoishamon, @joshua-white, @frankfeifan thank you very much for your comments! Yes please have rapidely a metting to provide me a good entry point to this subject.

2022-10-05 10:06 UTC, closed without merging