Implemented Killough relative permeability hysteresis
GEOSX/GEOSX pull request #1706
Opened 2021-12-06 23:54 UTC by francoishamon

This PR implements table relative permeability hysteresis using the Killough model for use in the Northern Lights test case. Testing on the NL drainage and imbibition non-wetting-phase relperm curves seems to produce meaningful results but will require some validation. 

The PR also slightly modifies `CompositionalMultiphaseBase.cpp` to allow for a history-dependent relperm, as we now need to do `relPerm.initializeState` and `relPerm.saveConvergedState` to initialize and save the max/min historical saturations in the constitutive model.

Current status:
- [X] Non-wetting-phase hysteresis
- [ ] Wetting-phase hysteresis (possibly in another PR)

2022-01-31 22:07 UTC, jafranc commented on src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
> +    // 4.4 Finally, we initialize the thermal conductivity
should be 4.5 ?

2022-01-31 22:09 UTC, jafranc commented on src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
should we repeat the note about pending thermal impl ?

2022-02-01 20:20 UTC, jafranc requested changes
Thanks @francoishamon for this nice PR, will be a great blueprint for capillary hysteresis.

2022-02-02 18:08 UTC, francoishamon commented on src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
> +    // 4.4 Finally, we initialize the thermal conductivity
Yes, I made the change

2022-02-02 18:11 UTC, jafranc approved these changes

2022-02-02 18:34 UTC, francoishamon commented on src/coreComponents/unitTests/constitutiveTests/testRelPerm.cpp
> +
I am using the `alpha` parameter for three-phase unit tests (to vary all the saturations at the same time), so it is not needed for two-phase flow.

2022-02-02 18:35 UTC, francoishamon commented on src/coreComponents/unitTests/constitutiveTests/testRelPermHysteresis.cpp
> +  TableFunction & imbibitionTable_g = dynamicCast< TableFunction & >(
Good idea, I added a small utility function in the `constitutiveTestHelpers` to initialize the tables `testRelPerm.cpp` and `testRelPermHysteresis.cpp`.

2022-02-02 18:35 UTC, francoishamon commented on src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
You are right. I added a note saying that the thermal implementation is not available yet.

2022-02-02 18:36 UTC, francoishamon commented on src/coreComponents/constitutive/relativePermeability/TableRelativePermeabilityHysteresis.hpp
> +    real64 const dSnorm_dS =  -ratio;
Good catch! This reminded me that we should add the wetting-phase case in the unit test that verifies the derivatives of the hysteretic relperms.

2022-02-02 18:37 UTC, francoishamon commented on src/coreComponents/unitTests/constitutiveTests/testRelPermHysteresis.cpp
> +class KilloughHysteresisTest : public ConstitutiveTestBase< TableRelativePermeabilityHysteresis >
For now, I left this as is. It is done in a similar way in `testRelPerm.cpp` and `testCapillaryPressure.cpp`, so we should probably change them all at once (if we want to change that).

2022-02-17 04:46 UTC, klevzoff approved these changes
Nice! I don't understand the model well enough to leave meaningful comments on the implementation, but I'm sure it's correct :)

2022-02-17 04:46 UTC, klevzoff commented on src/coreComponents/constitutive/relativePermeability/TableRelativePermeability.hpp
> +    static constexpr char const * relPermKernelWrappersString() { return "relPermWrappers"; }
Looks like you intended to use this string in wrapper registration, but forgot

2022-02-17 04:46 UTC, klevzoff commented on src/coreComponents/constitutive/relativePermeability/TableRelativePermeabilityHysteresis.cpp
> +void TableRelativePermeabilityHysteresis::initializePhaseVolFractionState( arrayView2d< real64 const, compflow::USD_PHASE > const & initialPhaseVolFraction ) const
It seems to me `initializePhaseVolFractionState` and `saveConvergedPhaseVolFractionState` are doing the same thing, essentially. Assuming `m_phaseMinHistoricalVolFraction` is initialized to `1.0` and `m_phaseMaxHistoricalVolFraction` is initialized to `0.0`, both computations amount to
```c++
minHistS[ip] = min( minHistS[ip], currentS[ip] );
maxHistS[ip] = max( maxHistS[ip], currentS[ip] );
```
I would just keep `saveConvergedPhaseVolFractionState` and call it when solver is initializing the models with initial saturation.

2022-02-17 04:54 UTC, klevzoff commented on src/coreComponents/constitutive/relativePermeability/TableRelativePermeabilityHysteresis.cpp
> +void TableRelativePermeabilityHysteresis::initializePhaseVolFractionState( arrayView2d< real64 const, compflow::USD_PHASE > const & initialPhaseVolFraction ) const
On a second thought, maybe this does not generalize well to all types of models. I'm struggling to come up with an example, but maybe are models for which "first time seeing state" and "update previously seen state" is a meaningful distinction that the model cannot figure out on its own, which necessitates having two functions in the interface.

2022-02-17 23:15 UTC, merged